[GS-39] 고객 요청 견적서 CRUD 구현
prgrms-be-devcourse/BE-04-GosuCatcher pull request #13
Opened 2023-09-03 10:21 UTC by hyee0715

## ✅ PR 유형
어떤 변경 사항이 있나요?

- [X] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [X] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정/삭제

## 📌 변경 내용 요약

- 고객 요청 견적서 단순 CRUD를 구현했습니다.

## 🔨 작업한 내용

- **MemberRequestEstimateController의 memberId와 subItemId는 @RequestParam으로 받게 했고, MemberRequestEstimateId는 @PathVariable로 받게 했습니다.**

- MemberRequestEstimateController에서 findAll()은 회원 id(memberId)로만 필터링 하여 특정 회원의 견적서들만 전체 조회하도록 했습니다.

- MemberRequestEstimateController의 메서드 이름을 create, findAll, findById, update, delete로 구성했는데, 네이밍이 괜찮은지 모르겠습니다. 수정해야 한다면 말씀 부탁드립니다.

- 테스트 코드 중 MemberRequestEstimateServiceTest는 mocking test 했고, MemberRequestEstimateControllerTest는 Rest docs 제외하고 작성했습니다!

- MemberRequestEstimate 필드 중 고객-고수 매칭의 중심이 되는 location(지역)은 현재 String으로 단순 구현이 되어있는데, 이후에 매칭 기능을 구현할 때 String으로 유지하고 `시/도` - `시/군/구` 형식에 맞게 유효성 검사를 추가하거나 형태를 변경할 가능성이 있을 것 같습니다! 현재는 null 검사만 해두었습니다.

## 💫 관련 링크

- [GS-39](https://gosu-catcher.atlassian.net/browse/GS-39) 

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [X] 커밋 메시지 컨벤션에 맞게 작성했습니다.  [Commit message convention](https://www.notion.so/backend-devcourse/Git-Convention-4920f2238bfa460798866c7de3da89a2) 참고  (Win : `Ctrl + 클릭` / Mac : `cmd + 클릭` 하세요. ~~페이지 이탈 방지~~) 
- [X] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

## 🙇🏽‍♂️ 기타 사항
- 컨벤션에 어긋나거나, 수정했으면 하는 부분들 말씀 부탁드립니다!!

2023-09-03 11:43 UTC, SW-H reviewed
수고하셨습니다..!!👍🏻👍🏻👍🏻👍🏻

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +		@RequestBody @Valid MemberRequestEstimateRequest memberRequestEstimateRequest) {
memberId랑 subItemId은 쿼리스트링으로 받는 이유가 있나요....? 

memberId는 path variable로 받고 나머진 그냥 다 body로 받는다던지 해도 될 것 같아서요!

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  	private LocalDateTime startDate;
현재시각보다 이후인지 검증을 해줘야 할 것 같아요! (견적을 받고자 하는 날짜가 견적을 요청한 시점보다 이전이 될 수 없도록요)

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  	@JoinColumn(name = "sub_item_id")
@OneToOne/ @ManyToOne 은 기본이 즉시로딩(Eager)인데 지연로딩(lazy)으로 설정하지 않으신 이유가 있을까요?

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/dto/request/MemberRequestEstimateRequest.java
> +	String detailedDescription) {
요것만 괄호가 파라미터랑 같은줄에 있는 것 같아요!

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +@Service
저희 `@Transactional` 클래스 단위에 붙이고 readOnly인 경우에만 메소드 단위에 붙이기로 했어요~

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +			memberRequestEstimateRequest.detailedDescription());
저희 update를 엔티티 내에서 하기로 한거 아닌가요? MemberRequestEstimate 클래스 내에 update 메소드 만들어서요!

2023-09-03 11:43 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
> +}
마지막 개행 통일해주면 좋을 것 같아요!!

2023-09-03 12:02 UTC, hongxeob requested changes
혜민님 고생하셨습니다! 복잡한 도메인 될 수 있는데 비교적 깔끔하게 잘해주신 것 같아요!
약속한 컨벤션들 몇가지와 그외 수정사항들 수정해주시면 될 것 같습니다 ㅎㅎ!

2023-09-03 12:02 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +	public ResponseEntity<MemberRequestEstimateResponse> update(@PathVariable Long memberRequestEstimateId,
업데이트는 ID만 우선 반환하는 걸로!

2023-09-03 12:03 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +		@RequestBody @Valid MemberRequestEstimateRequest memberRequestEstimateRequest) {
> memberId랑 subItemId은 쿼리스트링으로 받는 이유가 있나요....?
> 
> memberId는 path variable로 받고 나머진 그냥 다 body로 받는다던지 해도 될 것 같아서요!

저도 동의합니다~ 어차피 response dto에 세부 서비스 id가 있을테니 그것으로 조회하면 될 것 같고 url은 그냥 "/api/v1/member-request-estimates/userId/요청한견적서ID"가 되는 것이 나중에 유저별로 조회할 때도 좋을거 같아요!

2023-09-03 12:17 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +package com.foo.gosucatcher.domain.estimate.service;
아 이거 저도 말한다 하고 까먹었는데 짚어주셔서 감사해요~~

2023-09-03 12:21 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +		@RequestBody @Valid MemberRequestEstimateRequest memberRequestEstimateRequest) {
memberId와 subItemId를 어떻게 하면 좋을지 좀 고민을 했었는데요..! 

가장 먼저 subItem을 body에 넣지 않은 이유는 숨고 페이지의 url도 서비스마다 @pathVariable로 넣어서 구분하여 보여주더라구요! 저희도 그렇게 해보고자 일단 쿼리파라미터로 넣었습니다. 

memberId와 SubItemId를 @pathVariable이 아니라 @RequestParam으로 설정한 이유는 엔드포인트를 설정할 때 조금 지저분해보인다(?)고 느껴서 RequestParam으로 설정했습니다.

memberId와 SubItemId를 @pathVariabl로 설정하면 findById()나 update(), delete()를 호출하면 {memberRequestEstimateId}까지 @PathVariable로 들어가게 되어서 @PathVariable이 총 3개가 되는 경우가 생기는데, 
그러면 `"/api/v1/member-request-estimates/{memberId}/{subItemId}/{memberRequestEstimateId}"` 이런식으로,, url이 만들어지게 되어 엔드포인트가 깔끔하지 않다고 생각했습니다.

승원님이 말씀해주신 대로 memberId만 @PathVariable로 구현해도, 또 앞서 언급한 3개의 @PathVariable로 설정해도 무리 없을 것 같습니다. 팀원분들의 의견이 모아지는 대로 수정해보겠습니다!

2023-09-03 12:22 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +package com.foo.gosucatcher.domain.estimate.service;
수정했습니다!

2023-09-03 12:24 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +		@RequestBody @Valid MemberRequestEstimateRequest memberRequestEstimateRequest) {
고려하여 수정하겠습니다!

2023-09-03 12:27 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  	@JoinColumn(name = "sub_item_id")
수정했습니다.

2023-09-03 12:27 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/dto/request/MemberRequestEstimateRequest.java
> +	String detailedDescription) {
수정했습니다!

2023-09-03 12:28 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +@Service
넵 수정했습니다!

2023-09-03 12:30 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
> +}
마지막 개행은 어떻게 수정하면 될까요?

2023-09-03 12:33 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +			memberRequestEstimateRequest.detailedDescription());
현재 MemberRequestEstimate 클래스 내에 update 메서드를 

```java
public void update(String location, LocalDateTime startDate, String detailedDescription) {
	this.location = location;
	this.startDate = startDate;
	this.detailedDescription = detailedDescription;
}
```

이렇게 만들어놓은 상태인데, 어떻게 수정하면 될까요? 제가 이해를 잘 못한 것 같습니다ㅠㅠ

2023-09-03 12:47 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
> +}
```suggestion
}

```

2023-09-03 13:08 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +	public MemberRequestEstimateResponse create(Long memberId, Long subItemId,
일단 하위 서비스의 id를 body에 넣는 형식으로 바꾸겠습니다! 추후에 필요하면 이름을 넣는 방식으로 수정해보겠습니다~

2023-09-03 13:08 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +	public MemberRequestEstimatesResponse findAllByMember(Long memberId) {
추가했습니다!

2023-09-03 13:09 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +	public ResponseEntity<MemberRequestEstimatesResponse> findAll(@RequestParam(value = "member") Long memberId) {
수정했습니다!

2023-09-03 13:09 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
> +}
수정했습니다! 감사합니다~

2023-09-03 13:14 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/dto/request/MemberRequestEstimateRequest.java
> +package com.foo.gosucatcher.domain.estimate.dto.request;
수정했습니다!

2023-09-03 17:18 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +		memberRequestEstimate.update(memberRequestEstimateRequest.location(), memberRequestEstimateRequest.startDate(),
수정했습니다~

2023-09-03 17:18 UTC, hyee0715 commented on src/test/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateServiceTest.java
> +		MockitoAnnotations.openMocks(this);
적용했습니다!

2023-09-03 17:18 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/controller/MemberRequestEstimateController.java
> +	public ResponseEntity<MemberRequestEstimateResponse> update(@PathVariable Long memberRequestEstimateId,
수정했습니다. 감사합니다~

2023-09-03 17:23 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/service/MemberRequestEstimateService.java
> +			memberRequestEstimateRequest.detailedDescription());
수정했습니다! 감사합니다~

2023-09-03 18:06 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  	private LocalDateTime startDate;
추가했습니다! 감사합니다!

2023-09-04 02:39 UTC, hongxeob approved these changes

2023-09-04 02:39 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  		this.startDate = startDate;
```suggestion
		this.startDate = validateStartDate(startDate);
```

```
//엔티티로 이동
private void validateStartDate(LocalDateTime startDate) {
		if (LocalDateTime.now().isAfter(startDate)) {
			throw new BusinessException(ErrorCode.INVALID_START_DATE);
		}
	}
```
이렇게 하면 엔티티 안으로 캡슐화 할 수 있을 거 같은 느낌적인 느낌..!?

2023-09-04 02:39 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
> +		this.startDate = memberRequestEstimate.getStartDate();
```suggestion
		this.startDate = validateStartDate(memberRequestEstimate.getStartDate());
```
```
//엔티티로 이동
private void validateStartDate(LocalDateTime startDate) {
		if (LocalDateTime.now().isAfter(startDate)) {
			throw new BusinessException(ErrorCode.INVALID_START_DATE);
		}
	}
```
이렇게 하면 엔티티 안으로 캡슐화 할 수 있을 거 같은 느낌적인 느낌..!?

2023-09-04 06:12 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  		this.startDate = startDate;
수정했습니다!

2023-09-04 06:12 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
> +		this.startDate = memberRequestEstimate.getStartDate();
수정했습니다!

2023-09-04 10:05 UTC, kimihiqq approved these changes
혜민님 수고많으셨습니다!! 코드가 깔끔해서 보면서도 많은 참고가 되었습니다!👍👍
이미 꼼꼼하게 작성해주셔서 수정사항 보다는 오타나 궁금한점 위주로 리뷰드렸습니다!!

2023-09-04 11:24 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
> +	@OneToOne(fetch = FetchType.LAZY)
사실 저도 습관적으로 사용한 거라 큰 의미를 두지는 않았는데요! 아무래도 연관관계 관련 필드이다 보니 관리를 조금 더 유용하게 하기 위해서 그런 것이 아닌가~ 싶습니다. 이 부분은 로직적으로 필요하다면 하면 성현님 말씀대로 하는 것도 좋을 것 같습니다. 수정해야한다면 수정하겠습니다! 감사합니다~

2023-09-04 11:25 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/presentation/MemberRequestEstimateController.java
> +
엇 감사합니다!! 수정하도록 하겠습니다~

2023-09-04 13:15 UTC, SW-H approved these changes
고생하셨습니다💪🏻💪🏻💪🏻

detailedDescription에 대한 리뷰 뺴고는 참고만 하시면 될 것 같아요!!

2023-09-04 13:15 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/request/MemberRequestEstimateRequest.java
> +		return MemberRequestEstimate.builder()
```suggestion
		MemberRequestEstimateRequest memberRequestEstimateRequest) {

		return MemberRequestEstimate.builder()
```

2023-09-05 01:21 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
>  	private String detailedDescription;
detailedDescription은 선택사항이라 일단 길이 제한만 두도록 하겠습니다 ㅎㅎ

2023-09-05 01:22 UTC, hyee0715 commented on src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberRequestEstimateControllerTest.java
> +}
넵 추가했습니다~

2023-09-05 01:23 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/request/MemberRequestEstimateRequest.java
> +	String detailedDescription
수정했습니다!

2023-09-05 01:28 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/presentation/MemberRequestEstimateController.java
> +		return ResponseEntity.ok(memberRequestEstimateService.findAllByMember(memberId));
변경했습니다!

2023-09-05 04:44 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberRequestEstimateService.java
> +		List<MemberRequestEstimate> memberRequestEstimates = memberRequestEstimateRepository.findAllByMember(member);
이 부분은 맴버와 양방향 매핑을 고려해봐도 괜찮을거 같네요..?! 
아무래도 사용자쪽에서도 요청한 견적서를 모두 조회기능이 필요하기도 하고,
근데 양방향 매핑을 쓰는거 자체가 복잡성을 유발하니...! 
팀원분들하고 함께 상의해보는게 좋을거 같아요~

2023-09-05 04:52 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberRequestEstimateService.java
> +	public MemberRequestEstimateResponse create(Long memberId,
견적서를 새로 생성할 때, 이미 견적을 보낸 subItem에 관해서도 여러 번 견적을 보낼 수 있는건가요?!
서비스의 요구사항에 따라 다를 거 같긴한데, 만일 불가능하게 만든다면 이미 견적을 보낸 subItem에 관해서는
중복체크하는 로직이 필요할거 같습니다!

2023-09-05 05:00 UTC, Dev-Yesung approved these changes
고생하셨습니다 혜민님! 다른 분들이 리뷰달아주신게 많아서 서비스 요구사항 관련해서 생각해보려고 노력했습니다 ㅎㅎ 전체적으로 코드스타일은 깔끔하셔서! 리뷰 달은 부분은 팀원들과 함께 얘기해봐요~

2023-09-05 05:18 UTC, hyee0715 commented on src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberRequestEstimateService.java
> +	public MemberRequestEstimateResponse create(Long memberId,
이 부분 반영하도록 하겠습니다! 짚어주셔서 감사해요😊

2023-09-05 09:05 UTC, merged