[GS-35] 사용자 프로필(이미지) CRUD
prgrms-be-devcourse/BE-04-GosuCatcher pull request #18
Opened 2023-09-04 16:18 UTC by Dev-Yesung

## ✅ PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정/삭제

## 📌 변경 내용 요약
멤버 회원가입 CRUD, 멤버 프로필 이미지 CRUD 구현

## 🔨 작업한 내용
멤버 회원가입(+ 중복멤버 체크), 정보수정, 탈퇴, 멤버 프로필 이미지 업로드, 보기, 수정, 삭제 기능을 구현했습니다.
서비스 레이어의 일부 회원가입 관련 메서드를 유닛테스트로 작성했습니다.

다만, 현재 요구사항에 맞춰 구현했기 때문에 메서드들이 정확한 테스트를 작성하기 어렵고
추후 스프링 시큐리티를 통한 JWT 로그인을 구현하면, 메서드들이 크게 변경될 가능성이 높아
한계를 느껴 작성하다가 멈췄습니다.

프로필 이미지 관련 메서드는 크게 변경가능성이 없을거 같아 
다음 스플린트 때 작성해보도록 하겠습니다.

## 💫 관련 링크

- [GS-35](https://gosu-catcher.atlassian.net/browse/GS-35) 

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  [Commit message convention](https://www.notion.so/backend-devcourse/Git-Convention-4920f2238bfa460798866c7de3da89a2) 참고  (Win : `Ctrl + 클릭` / Mac : `cmd + 클릭` 하세요. ~~페이지 이탈 방지~~) 
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

## 🙇🏽‍♂️ 기타 사항

⚠️회원 가입, 관리 쪽 메서드가 부정확 혹은 부적절합니다.
추후 시큐리티를 붙일 경우 크게 변경될 예정이기 때문에, 
지금 코드리뷰를 하시면 무의미한 리뷰가 될 가능성이 높습니다...!
> 코드 스타일, (JPA사용관련)도메인, 프로필 이미지 업로드 관련 코드에 주로 리뷰해주시면 좋을 거 같습니다!

2023-09-05 01:13 UTC, hyee0715 approved these changes
예성님 고생 많으셨습니다! 말씀 남겨주신대로 프로필 이미지 위주로 코드를 봤는데, 예성님 스타일대로 잘 짜주신 것 같아서 별로 제가 코멘트 드릴 것이 없다고 느꼈습니다~ 굿굿 👍👍

2023-09-05 02:20 UTC, SW-H requested changes
예성님 너무너무 고생하셨습니다!!!애쓰신게 느껴지네요...!!....🥹
적어주신대로 프로필 이미지 위주로 보고 리뷰 남겨놓았습니다!!!

2023-09-05 02:20 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberSignUpRequest.java
> +	public static Member to(MemberSignUpRequest memberSignUpRequest) {
```suggestion
) {

	public static Member to(MemberSignUpRequest memberSignUpRequest) {
```

2023-09-05 02:20 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/member/infra/MemberProfileFileSystemRepository.java
> +		String extension = contentType.split("/")[1];
contentType 가져오기위해서 split 하는 부분이 아래에도 있던데
contentType을 반환해주는 메소드를 split사용하지 않는 이런 방식으로 작성하는건 어떨까요??

```java
import org.springframework.util.StringUtils;

public String getExtension(MultipartFile multipartFile) {
    String extension = StringUtils.getFilenameExtension(multipartFile.getOriginalFilename());

    return extension;
}
```

2023-09-05 02:20 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/member/infra/MemberProfileFileSystemRepository.java
> +		}
ImageFile 내에 기본이미지(default profile)인지 확인해서 반환해주는 메소드를 넣는건 어떨까요...? 
`getPath()`으로 빼올 필요도 없을 것 같아서요

2023-09-05 02:20 UTC, SW-H commented on src/main/java/com/foo/gosucatcher/domain/member/infra/MemberProfileFileSystemRepository.java
> +		}
```suggestion
		if (folder.exists()) {
		  	return;
		}
		boolean isCreated = folder.mkdir();
		if (!isCreated) {
			throw new MemberFileIOException(ErrorCode.INTERNAL_SERVER_ERROR);
		}

```

2023-09-05 04:22 UTC, kimihiqq approved these changes
예성님!! 수고많으셨습니다!! 👍👍👍
코드를 깔끔하게 작성해주셔서 리뷰드릴것이 별로 없어, 애너테이션 위주로 몇가지 리뷰 남겼습니다!!

2023-09-05 04:22 UTC, kimihiqq commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/ProfileImageUploadRequest.java
> +	@NotEmpty long memberId,
NotEmpty는 원시타입에는 적용되지 않는것으로 알고있습니다!

2023-09-05 05:53 UTC, hongxeob reviewed
예성님 이미지 관련해서도 작업하신다고 고생하셨습니다! 
정신없이 하시느라 몇가지 컨벤션, 레이어 역할등 헷갈리신거 같아요ㅎㅎ 몇가지 코드리뷰 남겨드렸으니 확인해 보시고 말씀해주세요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +	public MemberService(MemberRepository memberRepository, MemberProfileRepository memberProfileRepository) {
@RequiredArgsConstructor 써서 생성자 생략하는 것도 괜찮을것 같습니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +		Member member = MemberSignUpRequest.to(memberSignUpRequest);
각 데이터 값들의 유효성 검사를 해준 후에 엔티티 객체로 생성(변환)해주는게 좋을거 같아요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +	public void checkDuplicatedEmail(String email) {
다른 클래스에서도 사용이 되는 것이 아니라면 private으로 두고 @Transactional도 없어도 될듯합니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +		member.deleteMember();
여기 repository에서 멤버를 지우는 로직은 없는것 같아요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +		member.changeMemberInfo(memberInfoChangeRequest);
저희 update 부분도 dto가 아니라 entity로 변환하여 파라미터로 넘겨주기로 했어요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberLogInRequest.java
> +	@NotEmpty @NotBlank String password
데이터 유효성 검사할 때 message도 같이 넣어주면 개발자,사용자 입장에서 더 용이할 듯 합니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberSignUpRequest.java
> +	@NotEmpty @NotBlank @Min(2) @Max(20) String name,
```suggestion
	@Size(min = 2, max = 20 message = "message") String name
```
@Min, @Max 둘다 쓰는 것 보다 @Size 하나로 쓰고 그 안에서 최솟값, 최대값 지정 가능합니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberSignUpRequest.java
> +	public static Member to(MemberSignUpRequest memberSignUpRequest) {
+ 메서드명 toXXX (도메인명) 붙여주세요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
> +	public void changeMemberInfo(MemberInfoChangeRequest memberInfoChangeRequest) {
파라미터 DTO가 아닌 Entity로 받아주세요 !@~

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
> +			throw new InvalidValueException(ErrorCode.NOT_FOUND_IMAGE);
잘못된 값이 들어와서 InvalidValueException(Bad Request)인데 에러 메세지는 Not Found를 던저주는건 조금 안 맞는것 같습니다! 예외를 BusinessException(혹은 다른 커스텀 예외)으로 수정해주는건 어떨까요 ?

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/domain/MemberRepository.java
> +@Repository
어노테이션 제거하기로 했어요 !

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +public class MemberController {
많은 분들이 클래스단에 @RequiredArgsConstructor를 사용하셔서 생성자 대신 해주셨는데 통일하면 좋을 거 같습니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +	public ResponseEntity<Void> signUp(
보통 웹상에서 회원가입 완료하면 가입한 ID,Email 정도로 보여주며 XXX님 회원가입을 축하합니다 + email 정보등을 보여주는데 Void로 했을 때 어떤 장점이 있을까요?

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +			.body(response);
```suggestion
		return ResponseEntity.ok(response);
```
더욱 간편하게 한줄로도 처리 가능합니다!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +	}
이메일이 중복한지 찾는 기능은 보통 회원가입 할때 하지 않나요 ? 회원가입하는 로직에만 속해 있어도 충분할 것 같습니다!
어떤 서비스에서 회원가입하는 때 외에, 내 이메일이 중복인지 체크하는 기능이 필요하진 않을거 같아요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +		var response = memberService.findPassword(email);
저희 var에 대해서는 약속된게 없어서 명시적으로 타입을 적어주면 좋을거 같아요!

2023-09-05 05:53 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +}
컨트롤러는 각 서비스 레이어에 들어온 요청을 분기시켜주는 역할이 큰데, 이 메서드가 있는게 적절한지 저는 조금 헷갈리네요ㅠㅠ 팀미팅때 에프님께 한번 여쭤봐도 좋을거 같아요! 더불어 위의 Try Catch문도 조금 헷갈립니다!
따로 Util클래스를 만들어 사용하는 것도 나쁘지 않을것 같기도 해요ㅎㅎ

2023-09-05 12:51 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/infra/MemberProfileFileSystemRepository.java
> +		String extension = contentType.split("/")[1];
오... 이거 진짜 처음알았네요 감사합니다!

2023-09-05 13:16 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +	public void checkDuplicatedEmail(String email) {
중복이메일 검증 메서드는 컨트롤러에서도 사용합니다! GET에 쿼리 파라미터로 사용하도록 만들었습니다!

`
	@GetMapping("/signup")
	public ResponseEntity<Void> checkDuplicatedEmail(@RequestParam @Validated @Email String email) {
		memberService.checkDuplicatedEmail(email);
`

2023-09-05 13:47 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +	}
제가 생각한 방식은 회원가입 폼에서 
사용자가 이메일 중복검증 버튼을 눌렀을 때 호출하는 API를 만든것이었습니다.
예를 들어 프론트에서 구현할 때는 이메일 중복검증 과정을 안거치면 
회원가입완료 버튼이 활성화되지 않도록 만들기 위해서요~

홍섭님이 말씀하신건 signUp 메서드 내에 
checkDuplicated 메서드만으로도 충분하다는 말씀이신건가요?

2023-09-05 13:47 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/application/dto/request/MemberSignUpRequest.java
> +	@NotEmpty @NotBlank @Min(2) @Max(20) String name,
위쪽 리뷰에서도 비슷한 방식으로 @Length와@NotEmpty를 쓰는 것을 말씀해주셨는데,
일단 적용하기도 했고 ㅠ 디테일한 예외 메시지를 위해 기존 방식을 쓰도록 하겠습니다...!
나중에 유효성 검증할 때, 이 방식도 적용해야겠네요!! 알려주셔서 감사합니다👍

2023-09-05 13:47 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
> +	public void changeMemberInfo(MemberInfoChangeRequest memberInfoChangeRequest) {
헉 이건 진짜; 감사합니다...!

2023-09-05 13:47 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +	public ResponseEntity<Void> signUp(
맞습니다...! 홍섭님 말씀처럼 로그인 후 프론트에 보여줘야 할 스펙이 정해지고,
시큐리티로 구현된거였다면, 필요한 데이터를 반환해주려고 했는데
아무래도 시큐리티로 확장하게 되면 프론트에 반환해줘야 할 
데이터 부분에 변동이 클거 같아 1차 스플린트에서는 Void로 놔뒀습니다!
2차 스플린트 때 시큐리티 적용하고 홍섭님께서 말씀해주신 메시지 부분도 적용해보려고 합니다~
감사합니다!

2023-09-05 13:50 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/application/MemberService.java
> +		member.deleteMember();
deleteMember에서 isDeleted 필드에 true를 설정하는 소프트 딜리트 방식을 채택했습니다..!
회원에 관해서 이러한 삭제 방식이 부적절할까요? 판단이 안서서요...!

2023-09-05 13:57 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
> +			throw new InvalidValueException(ErrorCode.NOT_FOUND_IMAGE);
그렇네요! 적절한 비즈니스 예외 클래스 + 에러메시지를 수정해서 던지도록 하겠습니다

2023-09-05 15:57 UTC, Dev-Yesung commented on src/main/java/com/foo/gosucatcher/domain/member/infra/MemberProfileFileSystemRepository.java
> +		}
이 부분부터 시작해서 객체지향적인 코드가 많이 깨져있는 것을 확인했습니다..!
일단 수정하긴 했는데, 추후 리팩토링 과정이 많이 필요할거 같습니다 ㅠㅠ
일단 동작은 할 수 있도록 하드코딩 해놓은 부분이 있는데 다음 스플린트 때 변경해보도록 하겠습니다

2023-09-05 23:50 UTC, merged

2023-09-06 04:00 UTC, hongxeob commented on src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberController.java
> +	}
오 그러고보니 예성님 말씀이 맞겠네요! 이메일이 중복인지 확인하는 버튼이 있을테니 거기 사용될 용도인듯 합니다 ㅎㅎ!